Added the option to cherry pick hotfix commits to develop rather than merge
Conflicts:
	git-flow-hotfix

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -357,7 +357,7 @@ showcommands!     Show git commands while executing them
 
 cmd_finish() {
 	OPTIONS_SPEC="\
-git flow hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-k] [-n] [-b] <version>
+git flow hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-k] [-n] [-b | -c] <version>
 
 Finish hotfix branch <version>
 --
@@ -375,6 +375,7 @@ k,[no]keep            Keep branch after performing finish
 D,[no]force_delete    Force delete hotfix branch after finish
 n,[no]notag           Don't tag this hotfix
 b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
+c,cherrypick          Cherry Pick to $DEVELOP_BRANCH instead of merge
 "
 	local opts commit keepmsg remotebranchdeleted localbranchdeleted
 
@@ -391,6 +392,7 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	DEFINE_boolean 'force_delete' false "force delete hotfix branch after finish" D
 	DEFINE_boolean 'notag' false "don't tag this hotfix" n
 	DEFINE_boolean 'nobackmerge' false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
+	DEFINE_boolean 'cherrypick' false "Cherry Pick to $DEVELOP_BRANCH instead of merge" c
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "hotfix.finish.fetch"          "fetch"
@@ -405,6 +407,7 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	gitflow_override_flag_string    "hotfix.finish.signingkey"     "signingkey"
 	gitflow_override_flag_string    "hotfix.finish.message"        "message"
 	gitflow_override_flag_string    "hotfix.finish.messagefile"    "messagefile"
+	gitflow_override_flag_boolean   "hotfix.finish.cherrypick"     "cherrypick"
 
 	# Parse arguments
 	parse_args "$@"
@@ -425,6 +428,11 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	# Keeping both branches implies the --keep flag to be true.
 	if flag keepremote && flag keeplocal; then
 		FLAGS_keep=$FLAGS_TRUE
+	fi
+
+	# Check that not both no merge flags were given
+	if flag cherrypick && flag nobackmerge; then
+	    die "You can't use 'cherrypick' and 'nobackmerge' together."
 	fi
 
 	# Sanity checks
@@ -525,7 +533,40 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 		fi
 	fi
 
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+	if flag cherrypick; then
+		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+
+		local old_IFS=$IFS  # save the field separator
+		IFS=$'\n'           # new field separator, the end of line
+		for git_line in $(git log --format="%H %s" --reverse $MASTER_BRANCH..$BRANCH | grep -vE "^[a-z0-9]* Merge branch '[^'].*?'$"); do
+		        local commit_hash=$(echo $git_line | cut -d" " -f1)
+		        if [[ $(git log $DEVELOP_BRANCH --grep "$commit_hash" | wc -l) -eq 0  ]]; then
+		                echo -e "\n${LIGHTGREEN}Cherry picking: $git_line${NOCOLOR}"
+		                git_do cherry-pick -x -s $commit_hash
+		                if [[ $? -ne 0  ]]; then
+		                        echo -e "
+===============================================================
+= Cherry pick has conflicts, steps to continue:
+= 1. Fix the conflicts
+= 2. Stage the fixed file: '${BLUE}git add <file names>${NOCOLOR}'
+= 3. Continue the cherry pick: '${BLUE}git cherry-pick --continue${NOCOLOR}'
+=    *** If fixing the conflict results in an empty commit,
+=        you will need to run this command: '${BLUE}git commit --allow-empty${NOCOLOR}'
+= 4. Switch back to the hotfix branch: '${BLUE}git checkout $BRANCH${NOCOLOR}'
+= 5. Rerun the finish command: '${BLUE}git flow hotfix finish${NOCOLOR}'
+= OR run '${BLUE}git cherry-pick --abort${NOCOLOR}' to abort the cherry pick
+===============================================================\n"
+		                        die "Cherry pick failed for commit: $commit_hash"
+		                fi
+		        else
+		                echo -e "\n${LIGHTGREEN}Commit has already been Cherry Picked: $git_line${NOCOLOR}"
+		        fi
+		done
+		IFS=$old_IFS  # restore default field separator
+
+		git_do checkout $BRANCH || die "Could not check out branch '$BRANCH'."
+
+	elif [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
 		# By default we back-merge the $MASTER_BRANCH unless the user explicitly
 		# stated not to do a back-merge, in that case we use the $BRANCH.
 		if noflag nobackmerge; then
@@ -607,7 +648,9 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	if noflag notag; then
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
 	fi
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+	if flag cherrypick; then
+		echo "- All commits from the hotfix branch have been cherry picked into '$DEVELOP_BRANCH'"
+	elif [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
 		[ "$commit" = "$BASE_BRANCH" ] && echo "- Master branch '$BASE_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
 		[ "$commit" = "$VERSION_PREFIX$VERSION" ] && echo "- Hotfix tag '$VERSION_PREFIX$VERSION' has been back-merged into '$DEVELOP_BRANCH'"
 		[ "$commit" = "$BRANCH" ] && echo "- Hotfix branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
