Checkout can use partial name

diff --git a/git-flow-bugfix b/git-flow-bugfix
--- a/git-flow-bugfix
+++ b/git-flow-bugfix
@@ -604,10 +604,11 @@ showcommands!    Show git commands while executing them
 	# Parse arguments
 	parse_args "$@"
 
-	warn "The command 'git flow bugfix checkout/co' will be deprecated per version 2.0.0"
-	gitflow_require_name_arg
-
-	git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	NAME=$(gitflow_resolve_nameprefix "$NAME" "$PREFIX")
+	if [ $? -eq 0 ]; then
+		BRANCH=$PREFIX$NAME
+		git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	fi
 }
 
 cmd_co() {
