Perform git push before deleting branch
This addresses an issue when using a feature branch that is associated
with a pull request on GitHub when the develop branch is merge
protected.  In the current implementation of `git flow feature finish`,
the remote feature branch is deleted before the merged develop branch
has been pushed.  This causes the pull request to be closed before the
changes have been merged, so the approval no longer applies.  To a
certain extent this seems to be a bug with GitHub, but I don't see a
drawback to pushing before deleting the remote branch.

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -435,6 +435,10 @@ helper_finish_cleanup() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 
+	if flag push; then
+		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+	fi
+
 	remotebranchdeleted=$FLAGS_FALSE
 	localbranchdeleted=$FLAGS_FALSE
 
@@ -467,10 +471,6 @@ helper_finish_cleanup() {
 		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
 			gitflow_config_remove_base_section "$BRANCH"
 		fi
-	fi
-
-	if flag push; then
-		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
 	fi
 
 	echo
