Implement in-place release with -i/--inplace option
This implement a solution to issue #133 "Add ability to release directly
from develop".

When in-place is activated:

- the current branch must be merged in the develop branch
- no mergeback occurs
- no branch deletion occurs

The in-place release can be called in two ways:

    git flow release finish -i <version>

or a shorter form:

    git flow release -i <version>

* git-flow-release (cmd_default): Define flags of cmd_list() and
  cmd_finish() to support the shorter call form.
  Call cmd_finish() if inplace is enabled.
  (cmd_list): Avoid warning by redefining the verbose flag if called from
  cmd_default().
  (cmd_finish): Avoid warning by redefining flags if called from
  cmd_default().
  Add filter on the version.
  Do not merge back and delete branch when inplace is enabled

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -51,11 +51,33 @@ usage() {
 }
 
 cmd_default() {
-	cmd_list "$@"
+	# flags required for cmd_start
+	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean sign false "sign the release tag cryptographically" s
+	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
+	DEFINE_string message "" "use the given tag message" m
+	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean keep false "keep branch after performing finish" k
+	DEFINE_boolean notag false "don't tag this release" n
+	DEFINE_boolean nobackmerge false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
+	DEFINE_boolean inplace false "Release directly on the development branch" i
+	# flags required for cmd_list
+	DEFINE_boolean verbose false 'verbose (more) output' v
+
+	FLAGS "$@"
+	if flag inplace; then
+		cmd_finish "$@"
+	else
+		cmd_list "$@"
+	fi
 }
 
 cmd_list() {
-	DEFINE_boolean verbose false 'verbose (more) output' v
+	# cmd_default may already define flags
+	# at this stage we can not use parse_args
+	if [ -z "${FLAGS_verbose}" ]; then
+		DEFINE_boolean verbose false 'verbose (more) output' v
+	fi
 	parse_args "$@"
 
 	local release_branches
@@ -177,16 +199,32 @@ cmd_start() {
 }
 
 cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
-	DEFINE_boolean sign false "sign the release tag cryptographically" s
-	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
-	DEFINE_string message "" "use the given tag message" m
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
-	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean notag false "don't tag this release" n
-	DEFINE_boolean nobackmerge false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
+	# cmd_default may already define flags
+	# at this stage we can not use parse_args
+	if [ -z "${FLAGS_inplace}" ]; then
+		DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+		DEFINE_boolean sign false "sign the release tag cryptographically" s
+		DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
+		DEFINE_string message "" "use the given tag message" m
+		DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+		DEFINE_boolean keep false "keep branch after performing finish" k
+		DEFINE_boolean notag false "don't tag this release" n
+		DEFINE_boolean nobackmerge false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
+		DEFINE_boolean inplace false "Release directly on the development branch" i
+	fi
 
 	parse_args "$@"
+	# Run filter on the version
+	VERSION=$(run_filter_hook release-finish-version $VERSION)
+
+	# As VERSION might have changed reset BRANCH with new VERSION
+	BRANCH=$PREFIX$VERSION
+
+	if flag inplace; then
+		BASE="$(git_current_branch)"
+		git_is_ancestor "$BASE" "$DEVELOP_BRANCH" || die "Given base '$BASE' is not a valid commit on '$DEVELOP_BRANCH'."
+	fi
+
 	gitflow_require_version_arg
 
 	# Handle flags that imply other flags
@@ -210,13 +248,15 @@ cmd_finish() {
 
 	run_pre_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
-	# Try to merge into master.
-	# In case a previous attempt to finish this release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git checkout "$MASTER_BRANCH" || die "Could not check out $MASTER_BRANCH."
-		git merge --no-ff "$BRANCH" || die "There were merge conflicts."
-		  # TODO: What do we do now?
+	if noflag inplace; then
+		# Try to merge into master.
+		# In case a previous attempt to finish this release branch has failed,
+		# but the merge into master was successful, we skip it now
+		if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+			git checkout "$MASTER_BRANCH" || die "Could not check out $MASTER_BRANCH."
+			git merge --no-ff "$BRANCH" || die "There were merge conflicts."
+			  # TODO: What do we do now?
+		fi
 	fi
 
 
@@ -266,7 +306,7 @@ cmd_finish() {
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
 
 	# Delete branch
-	if noflag keep; then
+	if noflag keep && noflag inplace; then
 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
 			git checkout "$MASTER_BRANCH"
 		fi
@@ -285,7 +325,9 @@ cmd_finish() {
 	echo
 	echo "Summary of actions:"
 	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Release branch '$BRANCH' has been merged into '$MASTER_BRANCH'"
+	if noflag inplace; then
+		echo "- Release branch '$BRANCH' has been merged into '$MASTER_BRANCH'"
+	fi
 	if noflag notag; then
 		echo "- The release was tagged '$VERSION_PREFIX$VERSION'"
 	fi
@@ -294,7 +336,7 @@ cmd_finish() {
 	[ "$commit" = "$BRANCH" ] && echo "- Release branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
 	if flag keep; then
 		echo "- Release branch '$BRANCH' is still available"
-	else
+	elif noflag inplace; then
 		echo "- Release branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
