Wrong message is displayed upon a rebase

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -572,7 +572,7 @@ showcommands!    Show git commands while executing them
 	parse_args "$@"
 
 	if [ "$NAME" != "" ]; then
-		gitflow_expand_nameprefix_arg 
+		gitflow_expand_nameprefix_arg
 		base=$(git merge-base "$DEVELOP_BRANCH" "$BRANCH")
 		git_do diff "$base..$BRANCH"
 	else
@@ -598,7 +598,7 @@ showcommands!    Show git commands while executing them
 	parse_args "$@"
 
 	if [ "$NAME" != "" ]; then
-		gitflow_expand_nameprefix_arg 
+		gitflow_expand_nameprefix_arg
 		git_do checkout "$BRANCH"  || die "Could not check out branch '$BRANCH'."
 	else
 		die "Name a feature branch explicitly."
@@ -643,7 +643,7 @@ p,[no]preserve-merges  Preserve merges
 	require_clean_working_tree
 	require_branch "$BRANCH"
 
-    git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the feature branch '$BRANCH'."
+    git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't rebase the feature branch '$BRANCH'."
 
 	git_do checkout -q "$BRANCH"  || die "Could not check out branch '$BRANCH'."
 	if flag interactive; then
@@ -754,7 +754,7 @@ r,[no]remote     Delete remote branch
 	# Parse arguments
 	parse_args "$@"
 
-	gitflow_expand_nameprefix_arg 
+	gitflow_expand_nameprefix_arg
 
 	# Sanity checks
 	require_branch "$BRANCH"
