"git flow feature rebase" will rebase against its base branch instead of "develop"

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -274,7 +274,7 @@ Finish feature <name>
 h,help!        Show this help
 showcommands!    Show git commands while executing them
 F,fetch        Fetch from origin before performing finish
-r,rebase       Rebase instead of merge
+r,rebase       Rebase before merging
 k,keep         Keep branch after performing finish
 keepremote!    Keep the remote branch
 keeplocal!     Keep the local branch
@@ -286,7 +286,7 @@ no-ff!          Never fast-forward during the merge
 
 	# Define flags
 	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
-	DEFINE_boolean 'rebase' false "rebase instead of merge" r
+	DEFINE_boolean 'rebase' false "rebase before merging" r
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch"
 	DEFINE_boolean 'keeplocal' false "keep the local branch"
@@ -390,7 +390,7 @@ no-ff!          Never fast-forward during the merge
 
 	# If the user wants to rebase, do that first
 	if flag rebase; then
-		if ! git flow feature rebase "$NAME" "$BASE_BRANCH"; then
+		if ! git flow feature rebase "$NAME"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
@@ -656,15 +656,21 @@ i,interactive     Do an interactive rebase
 	gitflow_override_flag_boolean "FEATURE_REBASE_INTERACTIVE" "interactive"
 
 	expand_nameprefix_arg_or_current
-	warn "Will try to rebase '$NAME'..."
+
+	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+
+	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
 	require_clean_working_tree
 	require_branch "$BRANCH"
+	
+    git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the feature branch '$BRANCH'."
 
 	git_do checkout -q "$BRANCH"  || die "Could not check out branch '$BRANCH'."
 	if flag interactive; then
 		opts="$opts -i"
 	fi
-	git_do rebase $opts "$DEVELOP_BRANCH"
+	git_do rebase $opts "$BASE_BRANCH"
 }
 
 avoid_accidental_cross_branch_action() {
