Honor "keep" flag when pushing at "release finish" time
* git-flow-release (cmd_finish): Delete the release branch on remote only
  if the keep flag was not passed.
  In the other case, update the remote branch.

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -279,7 +279,11 @@ cmd_finish() {
 		if noflag notag; then
 			git push --tags "$ORIGIN" || die "Could not push tags to $ORIGIN."
 		fi
-		git push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		if noflag keep && git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			git push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		elif flag keep
+			git push "$ORIGIN" "$BRANCH" || die "Could not update the remote $BRANCH in $ORIGIN."
+		fi
 	fi
 
 	echo
