Refactoring of functions.
Refactor the function to override the flags to make them more like the
other functions in the program.

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -79,7 +79,7 @@ endswith() { [ "$1" != "${1%$2}" ]; }
 flag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -eq $FLAGS_TRUE ]; }
 noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }
 
-# _gf_determineBoolean
+# gf_determine_boolean
 # Check if given value can be interpreted as a boolean
 #
 # This function determines if the passed parameter is a valid boolean value.
@@ -91,7 +91,7 @@ noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }
 #	FLAGS_FALSE if the parameter is a boolean FALSE
 #	FLAGS_ERROR if the parameter is not a boolean
 #
-_gf_determineBoolean() {
+gf_determine_boolean() {
 	local _return _value
 	_value="${1}"
 	case "${_value}" in
@@ -108,55 +108,6 @@ _gf_determineBoolean() {
 	esac
 	unset _value
 	return ${_return}
-}
-
-# _gf_overrideBooleanFlag()
-#
-# Override a boolean flag
-#
-# Param $1: string The name of the environment variable
-# Param $2: string The flag name
-#
-_gf_overrideBooleanFlag() {
-	local _variable _env_var
-
-	_env_var="GITFLOW_FLAG_"$1
-	eval "_variable=\$${_env_var}"
-	if [ -n ${_variable} ]; then
-		_gf_determineBoolean ${_variable}
-		case "$?" in
-		${FLAGS_TRUE})
-			eval "FLAGS_${2}=${FLAGS_TRUE}"
-			;;
-		${FLAGS_FALSE})
-			eval "FLAGS_${2}=${FLAGS_FALSE}"
-			;;
-		${FLAGS_ERROR})
-			warn "Invalid value for ${2}"
-			;;
-		esac
-	fi
-	unset _variable _env_var
-	return ${FLAGS_TRUE}
-}
-
-# _gf_overrideStringFlag()
-#
-# Override a string flag
-#
-# Param $1: string The name of the environment variable
-# Param $2: string The flag name
-#
-_gf_overrideStringFlag() {
-	local _variable _env_var
-
-	_env_var="GITFLOW_FLAG_"$1
-	eval "_variable=\$${_env_var}"
-	if [ -n ${_variable} ]; then
-		eval "FLAGS_${2}=${_variable}"
-	fi
-	unset _variable _env_var
-	return ${FLAGS_TRUE}
 }
 
 #
@@ -486,6 +437,55 @@ gitflow_config_remove_base_branch() {
 
 	base=$1
 	$(git config --file=$GITFLOW_CONFIG --unset "branch.$branch.base" 2>/dev/null)
+}
+
+# gitflow_override_flag_boolean()
+#
+# Override a boolean flag
+#
+# Param $1: string The name of the environment variable
+# Param $2: string The flag name
+#
+gitflow_override_flag_boolean() {
+	local _variable _env_var
+
+	_env_var="GITFLOW_FLAG_"$1
+	eval "_variable=\$${_env_var}"
+	if [ -n ${_variable} ]; then
+		gf_determine_boolean ${_variable}
+		case "$?" in
+		${FLAGS_TRUE})
+			eval "FLAGS_${2}=${FLAGS_TRUE}"
+			;;
+		${FLAGS_FALSE})
+			eval "FLAGS_${2}=${FLAGS_FALSE}"
+			;;
+		${FLAGS_ERROR})
+			warn "Invalid value for ${2}"
+			;;
+		esac
+	fi
+	unset _variable _env_var
+	return ${FLAGS_TRUE}
+}
+
+# gitflow_override_flag_string()
+#
+# Override a string flag
+#
+# Param $1: string The name of the environment variable
+# Param $2: string The flag name
+#
+gitflow_override_flag_string() {
+	local _variable _env_var
+
+	_env_var="GITFLOW_FLAG_"$1
+	eval "_variable=\$${_env_var}"
+	if [ -n ${_variable} ]; then
+		eval "FLAGS_${2}=${_variable}"
+	fi
+	unset _variable _env_var
+	return ${FLAGS_TRUE}
 }
 
 #
