Using fetch flag fails sometimes.
When you use the fetch flag the command fails because the fetch fails when the remote branch doesn't exists. Add a check to see if the remote branch exists and if it does not issue an warning instead of an error.

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -253,7 +253,11 @@ git_fetch_branch() {
 	[ -n "$2" ] || die "Missing branch name"
 	origin="$1"
 	branch="$2"
-	git_do fetch -q "$origin" "$branch":refs/remotes/"$origin"/"$branch" || die "Could not fetch $branch from $origin."
+	if git_remote_branch_exists "$origin/$branch"; then
+		git_do fetch -q "$origin" "$branch":refs/remotes/"$origin"/"$branch" || die "Could not fetch $branch from $origin."
+	else
+		warn ("Trying to fetch branch $origin/$branch but it does not exist.")
+	fi
 }
 
 #
