Implement --keep[local|remote] in release

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -111,6 +111,15 @@ git_remote_branch_exists() {
 	[ -n "$(git for-each-ref --format='%(refname:short)' refs/remotes/$1)" ]
 }
 
+git_remote_branch_delete() {
+	[ -n "$1" ] || die "Missing branch name"
+	if git_remote_branch_exists "$ORIGIN/$1"; then
+		git push "$ORIGIN" :"$1" || die "Could not delete the remote $1 in $ORIGIN."
+	else
+		warn "Trying to delete the remote branch $1, but it does not exists in $ORIGIN"
+	fi
+}
+
 git_branch_exists() {
 	[ -n "$1" ] || die "Missing branch name"
 	git_local_branch_exists "$1" || git_remote_branch_exists "$1"
