Version is required only in finish: git-flow-hotfix
The first parameter of "git flow hotfix" commands became the name of the
hotfix branch execpt for "finish".

This modify mostly the pre/post hooks, their firt "<version>" parameter
is suppressed.

The new semantic of "git flow finish" is the following:

- if "<name>" parameter is passed use it as branch to merge
- else if no "<name>" parameter, use "hotfix/<version>" as branch to merge
- else if "hotfix/<version>" branch does not exists and the current
  branch is a hotfix one, use the current branch

* gitflow-common: New helpers to check the "type" of the current branch
  name.
  (require_current_branch_prefix): Test if the current branch name start
  with the prefix passed as first argument.
  (require_current_feature_branch): Test if the current branch is a
  feature.
  (require_current_release_branch): Test if the current branch is a
  release.
  (require_current_hotfix_branch): Test if the current branch is a hotfix
  (require_current_support_branch): Test if the current branch is a
  support.

* git-flow-hotfix (cmd_list): Fix warn message.
  (parse_args): First parameter is name for most
  functions, define it here.
  (cmd_start): No more use of version filter.  Require name argument
  instead of version argument.  The pre and post hooks have one parameter
  less.  Update help message.
  (cmd_publish): Require name argument instead of version argument.  The
  pre and post hooks have one parameter less.
  (cmd_track): Require name argument instead of version argument.
  (cmd_finish): First argument is version.  Run version filter
  hotfix-finish-version.  Set $BRANCH in order of preference to: 1.) the
  second argument passed, 2.) "<hotfix prefix>/<version>", 3.) the
  current branch if a hotfix.  Require name argument instead of version
  argument.  The pre and post hooks have one parameter less.
  (cmd_delete): Remove $VERSION from hooks calls.

* hooks/filter-flow-hotfix-finish-version: Version filter for hotfix
  finish.
  Differ in old hooks/filter-flow-hotfix-start-version by adding $ORIGIN
  and $BRANCH parameters.

* hooks/pre-flow-hotfix-start: Remove VERSION as first argument.

* hooks/post-flow-hotfix-start: Ditoo.

* hooks/pre-flow-hotfix-publish: Ditoo

* hooks/post-flow-hotfix-publish: Ditoo

* hooks/pre-flow-hotfix-delete: Ditoo.

* hooks/post-flow-hotfix-delete: Ditoo

* hooks/pre-flow-hotfix-finish: Fix comment.

* hooks/post-flow-hotfix-finish: Fix comment.

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -413,6 +413,35 @@ require_branches_equal() {
 	fi
 }
 
+require_current_branch_prefix() {
+	local prefix="$1"
+	local branch=$(git_current_branch)
+	[ -n "$prefix" ] || die "Fatal: Prefix parameter missing."
+	[ "${branch#$prefix}" != "$branch" ]
+}
+
+require_current_feature_branch() {
+	require_current_branch_prefix $(git config --get gitflow.prefix.feature) \
+	    || die "Current branch is not a feature"
+}
+
+require_current_release_branch() {
+	require_current_branch_prefix $(git config --get gitflow.prefix.release) \
+	    || die "Current branch is not a release"
+}
+
+require_current_hotfix_branch() {
+	local branch=$(git_current_branch)
+	require_current_branch_prefix $(git config --get gitflow.prefix.hotfix) \
+	    || die "Current branch is not a hotfix"
+}
+
+require_current_support_branch() {
+	local branch=$(git_current_branch)
+	require_current_branch_prefix $(git config --get gitflow.prefix.support) \
+	    || die "Current branch is not a support"
+}
+
 #
 # Show commands if flag is set.
 #
