Only fetch the given branch.
Introduces a new function git_fetch_branch.

When fetching a branch from a remote we only want to fetch the given
branch. Before the fetch would fetch the remote but store it in
FETCH_HEAD and do nothing with this. This meant that checks like
require_branch_equal not work correctly when given the fetch flag.

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -183,6 +183,25 @@ git_is_branch_merged_into() {
 git_is_ancestor() {
 	git_is_branch_merged_into $1 $2
 }
+
+#
+# git_fetch_branch()
+#
+# $1 Origin - Where to fetch from
+# $2 Branch - Which branch to fetch
+#
+# This fetches the given branch from the given origin.
+# Instead of storing it in FETCH_HEAD it will be stored in
+# refs/remotes/<origin>/<branch>
+#
+git_fetch_branch() {
+	[ -n "$1" ] || die "Missing origin"
+	[ -n "$2" ] || die "Missing branch name"
+	local orgin="$1"
+	local branch="$2"
+	git fetch -q "$origin" "$branch":refs/remotes/"$origin"/"$branch" || die "Could not fetch $branch from $origin."
+}
+
 #
 # gitflow specific common functionality
 #
